### ISSUE TITLE
Prince of Persia Trilogy (PS3) .bf files (partially) not supported

### ISSUE THREAD

**Issue by icup321** [RetingencyPlan/le_quickbms_script_compendium#4]
So I felt like making this a separate issue.

I looked further into the POP Trilogy for PS3 and it looks like some of the .bf files don't work with sally_bf.bms. I am able to extract the prince.bf file from all 3 games, but the sound.bf, textures.bf, and geometry.bf files all fail to extract. I found out that the headers for these unsupported .bf files were completely different, unlike anything I've seen, so maybe they are using different formats?

**Comment by AnonBaiter** [comment]
well, yeah. see if you can look at these things through an hex editor.

**Comment by icup321** [comment]
So I went back to check on this and I found out that those .bf files are actually Yeti engine archives and can be extracted: https://zenhax.com/viewtopic.php?t=4754

So it seems this version uses a combination of two engines, weird, but not surprising for Ubisoft.
