### ISSUE TITLE
Naruto: The Broken Bond (X360) Unsupported .bf file

### ISSUE THREAD

**Issue by icup321** [RetingencyPlan/le_quickbms_script_compendium#8]
I've found another Jade engine game that seems to be incompatible with sally_bf.bms.
Naruto: The Broken Bond seems to use the BF64 format, which afaik, Shaun White Skateboarding (Wii version) is the only other game I know of that uses it.
![bf64](https://user-images.githubusercontent.com/28464642/151606494-cf10e324-c433-4c69-b13f-5e0138454356.PNG)
When I attempt to extract it, this error comes up (also I'm not sure what's up with filename compatibility thing that pops up):
![narutoerror](https://user-images.githubusercontent.com/28464642/151606989-ebd0532f-4351-44b2-9a30-0ceac932a51f.PNG)

Out of all the Jade engine games I've tested, I think this is the only one left that is unsupported. I've made an extensive list of all the Jade and LyN engine games I could find here:
https://raymanpc.com/wiki/en/Jade_(engine)
https://raymanpc.com/wiki/en/LyN
I tried my best to make sure all of the platforms are accurate, though if there's anything I'm missing or wrong, don't hesitate to correct me.

**Comment by RetingencyPlan** [comment]
fixed the BF64 extraction issue with naruto.bf from Naruto The Broken Bond.

as far as my feedback on the lists go, i think you're missing an LyN-based game in there. it has a name of **MotionSports** and was an Kinect-exclusive Xbox 360 title released by Ubisoft in 2010. i managed to find out some bf archives from within the game files that had this "ABE" format. most of them are all compressed into some LZX-based container though.

**Comment by icup321** [comment]
Alright, thanks for the help! I also see you added support for TMNT: Turtles In Time Re-Shelled. I knew it used LyN because someone told me it did, but I never did actually test sally_bf.bms on it, so thanks for that too.

**Comment by modusc896d352** [comment]
you're welcome.
